AccountsCollection.permit(['insert', 'update', 'remove']).apply();
Contacts.permit(['insert', 'update', 'remove']).apply();
Manufacturers.permit(['insert', 'update', 'remove']).apply();
PackageTypes.permit(['insert', 'update', 'remove']).apply();
Products.permit(['insert', 'update', 'remove']).apply();
Quotes.permit(['insert', 'update', 'remove']).apply();
LineItems.permit(['insert', 'update', 'remove']).apply();
PdfsCollection.permit(['remove']).apply();
Settings.permit(['update']).apply();
CustomerTypes.permit(['insert']).apply();
Comments.permit(['insert']).apply();